### ISSUE TITLE
Can I use somehow FragmentBreadCrumbs ?

### ISSUE THREAD

**Issue by mlt** [JakeWharton/ActionBarSherlock#133]
I see there is [_setBreadCrumbTitle_](https://github.com/JakeWharton/ActionBarSherlock/blob/master/library/src/android/support/v4/app/FragmentTransaction.java#L229) method and alike available for _android.support.v4.app.FragmentTransaction_. However I can't seem to find a substitute for _android.app.FragmentBreadCrumbs_. Is it intentionally?

**Comment by JakeWharton** [comment]
Those classes come from the Android Compatibility Package which does not contain support for fragment bread crumbs. **Please** file a feature request for this on http://b.android.com as I think we'd all like to see it.

I'm going to close this as I am refocusing this library for v4.0 on providing and supporting only the action bar component and not maintaining separate enhancements to the entire compat lib. That's not to say, however, that I won't backport this as a small standalone .jar once 4.0 is released.

**Comment by JakeWharton** [comment]
Took a quick look at the sources, other than requiring a few resources there's no reason why this can't be implemented for the compat lib as far as I can tell. This does mean that until ADT supports bundling resources in .jar files that it will have to be consumed as a library project (or apklib if you're using maven).

I'll take a stab at this next week. You may want to "watch" my [profile on GitHub](https://github.com/JakeWharton), follow me [on Twitter](http://twitter.com/JakeWharton), or circle me [on G+](http://profiles.google.com/jakewharton) in order to see the announcement as it will definitely be in a separate repo.

**Comment by JakeWharton** [comment]
Proof of concept is working. Needs a bit of polish before a 1.0 release. Follow at https://github.com/JakeWharton/HanselAndGretel
