### ISSUE TITLE
Intermediate Progress Display is Gray rather than Blue on 3.1

### ISSUE THREAD

**Issue by eburnette** [JakeWharton/ActionBarSherlock#167]
Trying the beta sample on an Android 3.1 tablet, I noticed that when I turned on the Intermediate Progress Display, it shows a gray rotating circle instead of the Honeycomb standard blue one. I believe gray is the Ice Cream Sandwich color.

**Comment by eburnette** [comment]
Interestingly if you also turn on Tabs navigation mode along with Intermediate Progress Display, you can see both a blue and a gray spinning circle on the screen at once.

**Comment by JakeWharton** [comment]
This is intended behavior of sorts. The whole concept of ABS (especially with v4) is to provide an action bar which looks the same across all devices and API levels. As such, I had to implement my own version of `ProgressBar` within the library itself in order to properly provide custom theming for it. I chose to go with the ICS style since that's the theme of everything else.

It would be trivial, however, to support the blue style on Honeycomb, I'm just not sure if it's what I want to do. I'll have to experiment with it and see how it looks (since the HC and ICS blues are very different). I'll leave this open as a reminder.

And the reason the tabs are blue is because its using the system `ProgressBar` as just an example of custom views in tabs. I understand why that is a jarring experience. I should probably change that demo regardless so this doesn't happen on any device < ICS.

**Comment by eburnette** [comment]
I'd like to be able to use Theme.DeviceDefault and have everything including the action bar pick up the device specific colors and styles as described in http://android-developers.blogspot.com/2012/01/holo-everywhere.html . So for example if HTC Sense for Android 4 makes the device default use shades of green instead of blue or gray, I want to see green in my app as well so it will fit in.

**Comment by JakeWharton** [comment]
The problem with allowing native styling to be applied is that while some vendors may be polite and only change the drawables, others will change the size, padding, and/or margins of the default indeterminate progress bar widget which will effect how it is positioned. I'm taking the view of the entire action bar functioning as a single custom widget and therefore will have its own styling independent of the system (on pre-4.0).

Since the action bar is highly themable, however, it's not impossible to achieve a native look simply by having a custom theme for the action bar and specifying the following:

``` xml
<item name="indeterminateProgressBarStyle">?android:attr/indeterminateProgressBarStyle</item>
```

This should accomplish what you are looking for.

Now as to whether or not I'll be providing a built-in theme for this remains to be seen. I am in the process of rewriting the themes right now to include all three of the system variants. I probably will be providing a version that inherits from `Theme.DeviceDefault` on API 14+ but I'll have to consider whether that same theme should also attempt to apply native styling the appropriate things on pre-4.0 as well.

I'm going to move this to the v4.0.1 milestone since my main concern is just getting the core functionality and look done.

**Comment by JakeWharton** [comment]
I've decided not to add this to the core of the library since the Honeycomb market share should be dwindling.

To add it yourself you need only do something like the following:

``` xml
<!-- values-v11/ -->
<style name="Theme.MyTheme" parent="Theme.Sherlock">
    <item name="actionBarStyle">@style/Widget.MyTheme.ActionBar</item>
</style>
<style name="Widget.MyTheme.ActionBar" parent="Widget.Sherlock.ActionBar">
    <item name="indeterminateProgressStyle">@android:style/Widget.Holo.ProgressBar.Large</item>
</style>
```

The only downside of this is that the Honeycomb blue and the ICS blue clash a bit so you'd also probably want to set the action bar background to `@null` or something if you weren't already providing a custom background.

**Comment by eburnette** [comment]
Ok, thanks

-----Original Message-----
