### ISSUE TITLE
ActionBarSherlock#handleNative() doesn't accept custom ActionBarHandlers

### ISSUE THREAD

**Issue by petedoyle** [JakeWharton/ActionBarSherlock#17]
Currently `handleNative(Class<? extends NativeActionBarHandler>)` requires that any native handler extend `NativeActionBarHandler`.  Unfortunately, almost everything in NativeActionBarHandler is declared `final` so its functionality can't be overridden.

I'd like to propose changing handleNative to `handleNative(Class<? extends ActionBarHandler<android.app.ActionBar>>)` to allow for custom native handlers.

**Comment by JakeWharton** [comment]
Out of curiosity, what functionality were you trying to extend that was prevented?

The reason that a lot of the overrides within the `NativeActionBarHandler` are `final` is because their implementation is so direct it was hard for me to see a use-case where someone would need to override them. For example, when the sherlock calls `setTitle(int)` on the handler and it is for the native action bar, the call is simply marshaled along to the action bar itself.

I can see why perhaps this would make sense if someone wanted to provide a wholly custom implentation for the native action bar but I'm just struggling to see what exactly is missing that needs the override?

**Comment by JakeWharton** [comment]
Your concern becomes invalid with the new API in the dev branch. On Android 3.0+ you interact with the native action bar using its native API except by calling `getSupportActionBar()` instead of `getActionBar()`.

Release will be by the end of this month.
