### ISSUE TITLE
Additional themes, please

### ISSUE THREAD

**Issue by ai212983** [JakeWharton/ActionBarSherlock#173]
Now its pain to implement dark action bar on light content. It would be awesome to have ABS themes extending Theme.Holo.Light.DarkActionBar, for example.

**Comment by chrisbanes** [comment]
I did add this in #126 but @JakeWharton reverted it before v3.5.1 was released. Not sure why.

**Comment by ai212983** [comment]
I guess it was made to avoid style changes in three different places... Planned to be in 4.0, though. Bad thing its quite unclear when 4.0 is out. =(

**Comment by ai212983** [comment]
Actually, main problem with dark actionbar on white content for me is dark text color of action pupup menu items. Any suggestion how I can style it properly?

**Comment by chrisbanes** [comment]
I couldn't work out how to fix that, so just changed the popup background back to the light one.

**Comment by ai212983** [comment]
Just if someone will run into the same problem: you can do it with a hack, overriding primary text color in your Theme.Sherlock.Light subtheme, like: `<item name="android:textColorPrimary">#ffffffff</item>`

Will work fine with simple apps, when you can control every UI element.

**Comment by JakeWharton** [comment]
`Theme.Holo.Light.DarkActionBar` was introduced in API 14 and ABS 3.x only officially supports compiling against API 13. Of course, API 14 and 15 are easy enough to support as a compilation target by simply adding a few default method implementations to `MenuItemImpl` and `MenuItemWrapper`. This has other implications, however, which is why it hasn't been done officially.

@chrisbanes I had a problem with something with the implementation which was the reason for the last-minute pull. List navigation perhaps? I can't remember. I was in a hurry to release the null Bundle fix since I had gotten about 4 emails and 2 pull requests with patches and people prodding for it.

**Comment by JakeWharton** [comment]
I'm going to close this for now. It will be present in 4.0 (which I'm targetting for end of the month, fingers crossed!). It shouldn't be terribly difficult for someone to implement this themselves to the degree that's required for their implementation. You should be providing your own style customization anyways.
