### ISSUE TITLE
Allow derivation from Android's Holo and DeviceDefault themes

### ISSUE THREAD

**Issue by beafdefx** [JakeWharton/ActionBarSherlock#180]
Currently ABS requires the app to inherit from Theme.Sherlock or Theme.Sherlock.Light, which in turn derive from android:Theme.NoTitleBar and android:Theme.NoTitleBar.Light.  This has suddenly become a problem for me because I manage an app that gets preloaded on third party devices (in addition to having a market presence), and one of our partners is insisting that we derive from DeviceDefault themes so they can have some control over the general look and feel of all the apps preloaded on their devices.  DeviceDefault is Android's way of giving device providers a basis on which to apply their customizations to the core Holo theme:

http://android-developers.blogspot.com/2012/01/holo-everywhere.html

It would be really awesome for us to be able to have an ABS theme to use that itself derives from DeviceDefault.  Similarly, I'm sure others might want to be able to derive from Holo directly.

If there is a quick hack that you know will work across devices, even if it means modifying ABS source, that would be really great for me to know ASAP, but I'm registering this as a feature request because I'm sure a formal solution would be appreciated by many going forward.

**Comment by JakeWharton** [comment]
This will be provided by ABS 4 (#143).

In order to do this with v3.x, just copy the `abs__styles.xml` from the `values-v11/` folder to `values-v14` and change the parent to the appropriate `DeviceDefault` theme. You will, of course, have to compile with Android 4.0 which means implementing a few empty methods in `MenuItemImpl` and `MenuItemWrapper` for the three or four new methods added to the `MenuItem` interface in ICS.

I'm not going to put this in the repository since I don't want to impose using 4.0 for compilation.

Going to close this but if you have any more questions about accomplishing this don't hesitate to post on the forum (http://abs.io/forum) or email me directly. Best of luck!

**Comment by beafdefx** [comment]
Thanks for the quick response.  The short term plan sounds like it will work.

**Comment by JakeWharton** [comment]
If you have any troubles feel free to post on the forum http://abs.io/forum or email me directly.

**Comment by JakeWharton** [comment]
Whoops. I already said that... haha. Doing a lot of emails tonight :-)
