### ISSUE TITLE
in actionmode you can press on stuff in the actionbar

### ISSUE THREAD

**Issue by daverix** [JakeWharton/ActionBarSherlock#209]
When using actionmode in ABS4.0 beta 5 I can click on my spinner and action items below the action mode bar. I'm using Android 2.3.4.

**Comment by SimonVT** [comment]
This appears to be because the animation is not being cleared from the ActionBarView after it's done animating visibility.

The ViewGroup does the following check before passing on a touch event:
if ((child.mViewFlags & VISIBILITY_MASK) == VISIBLE || child.getAnimation() != null)

getAnimation() on ActionBarView never returns null on <=2.3, while it correctly does so on 3.0+.

**Comment by JakeWharton** [comment]
Damn. That's going to be tricky...

**Comment by SimonVT** [comment]
An alternative way to handle this is to intercept the touchevent in ActionBarView if visibility != VISIBLE.

@Override
public boolean onInterceptTouchEvent(MotionEvent ev) {
    return getVisibility() != VISIBLE;
}

This will at least ensure that the child views do not get a touch event when the ActionBarView is GONE.
