### ISSUE TITLE
list navigation in actionbar, the text font color is wrong.

### ISSUE THREAD

**Issue by virsir** [JakeWharton/ActionBarSherlock#223]

**Comment by JakeWharton** [comment]
This has been a bug for the last few betas. Spinner's are the worst widget ever :(

**Comment by gentlecat** [comment]
I have the same issue. It's always black.
![Example ](http://tsukanov.me/stuff/simple-counter/screenshots/1.png)

**Comment by gabrielittner** [comment]
It's just using the opposite color as it should be. On black theme the font is black, on light it's white.

**Comment by JakeWharton** [comment]
The issue is far from being that simple, unfortunately. The problem is the default list item layout is hard coded to use a specific color setting in the theme which is always wrong because of how Spinners normally have a contrasting background. You can see evidence of this all over StackOverflow and the developer mailing list when people try to do the same thing.

The way it was solved in ABSv3 was requiring users to use a custom layout for the contents. I'm not sure there will be any other way to do for this either.

I hate Spinners...
