### ISSUE TITLE
Custom background on ICS causes icon and title to disappear  

### ISSUE THREAD

**Issue by davidvavra** [JakeWharton/ActionBarSherlock#235]
Hi,
I tried to customize actionbar background on ICS using "android:" directive like this:

```
<style name="SettleUpTheme" parent="@style/Theme.Sherlock.Light.DarkActionBar">
    <item name="android:actionBarStyle">@style/CustomActionBar</item>
</style>

<style name="CustomActionBar" parent="Widget.Sherlock.ActionBar">
    <item name="android:background">@drawable/actionbar_background</item>
</style>
```

Background is changed, but I don't see actionbar logo and title anymore. For logo, I have android:logo set in manifest.

**Comment by JakeWharton** [comment]
You'll need to use `android:Widget.Holo.ActionBar` as the parent for your `-v14` version of the style. Or you could update to the latest version from the `4.0-wip` branch.

I stupidly forgot to include native versions of all the widget styles. I should update the beta on the site with that commit since I assume most people will fall into the same trap.
