### ISSUE TITLE
onConfigurationChanged and <FROYO

### ISSUE THREAD

**Issue by MarcusWolschon** [JakeWharton/ActionBarSherlock#236]
public void onConfigurationChanged(Configuration newConfig) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.FROYO) {
            super.onConfigurationChanged(newConfig);
        }

This doesn't make any sense.
On devices <FROYO this class couldn't even be loaded because it references a non-existing method "onConfigurationChanged".
So that method couldn't possibly get executed on such a device.
Classic ClassNotFoundError .

**Comment by JakeWharton** [comment]
The Android 2.1 classloader will rewrite the byte code of the class during
load to throw a NoSuchMethodError but since it's wrapped in an if block it
will never be executed. It'll log a nasty warning but that's better than
Android 1.6 which would kill the whole class being loaded.
On Feb 9, 2012 7:28 AM, "Marcus Wolschon" <
reply@reply.github.com>
wrote:

**Comment by MarcusWolschon** [comment]
Oh, i wasn't aware they changed this in 2.1 .
