### ISSUE TITLE
Forced overflov menu do not work on ICS

### ISSUE THREAD

**Issue by mykola-dev** [JakeWharton/ActionBarSherlock#239]
I found that with new beta there is no overflow menu button on ICS. Even in example demo app.

**Comment by JakeWharton** [comment]
There is no such option on ICS natively. Unless we can figure out a way to make `ViewConfiguration.get(context).hasPermanentMenuKey()` return `false`... perhaps with a `ContextThemeWrapper`? I'll have to investigate.

**Comment by JakeWharton** [comment]
Nope, sorry. It's impossible. Just pray all real ICS devices follow Googles recommendation of omitting the menu key.

**Comment by mykola-dev** [comment]
But with native action bar we can do this. I was thinking that there is default behavior. And in this article 
http://android-developers.blogspot.com/2012/01/say-goodbye-to-menu-button.html
says "Your activities should provide buttons for important user actions directly in the action bar (or elsewhere on screen). Those that can’t fit in the action bar end up in the action overflow."

**Comment by JakeWharton** [comment]
The problem is that we have no way of controlling whether or not the native action bar shows the overflow item or not. It's done deep within the system. The perfect example is the emulator since it will never show an overflow item due to there being a hardware menu key on the skin (even disabling the skin won't enable it though).

This is how the system determines the property: https://github.com/android/platform_frameworks_base/blob/master/core/java/android/view/ViewConfiguration.java#L307-309

**Comment by SimonVT** [comment]
It IS default behavior to hide the overflow button on devices with a menu key. The native action bar is shown on ICS devices, not the ABS implementation.

**Comment by mykola-dev** [comment]
Oh, I see now. Thanks for the clarification. I have tested the app on emulator with menu button enabled.

**Comment by SimonVT** [comment]
@JakeWharton you can get the emulator to show software keys if you want. Just set the "Hardware Back/Home keys" property to no from the GUI avd editor.

**Comment by JakeWharton** [comment]
You can, but that still doesn't disable the system thinking that it has a hardware key. I talked to Xavier about this a few weeks ago when they first added that feature so hopefully future versions of the SDK will fix that tiny bug.

**Comment by SimonVT** [comment]
Huh, it does show the overflow button for me tho.

**Comment by mykola-dev** [comment]
It was a bug but seems they fixed it with last sdk release

**Comment by JakeWharton** [comment]
Oh, excellent!

**Comment by yuvidroid** [comment]
Sorry to resurrect this after 3 months. But...I'd like to always have the "overflow menu" shown, even on ICS devices with an hardware menu key. I know that the native ICS ActionBar won't show the overflow item, but is there a (simple) way to force the ABS implementation of the ActionBar even on API 14+? Thanks!

**Comment by JakeWharton** [comment]
Nope, sorry. It's impossible. Just pray all real ICS devices follow Googles recommendation of omitting the menu key.

**Comment by arusahni** [comment]
Sadly it appears Samsung is thumbing their nose at Google with the S3.  Granted, I can see why they'd prefer this to having to create the navbar menu button on devices with hardware buttons (e.g. the One X).  Still annoying.

**Comment by yuvidroid** [comment]
Just take all the existing devices that are being upgraded to ICS....Nexus S runs ICS and it has an hardware menu button, same goes for the Galaxy S2. :(
Anyway, coming back to my question, maybe I didn't explain myself very well. What I'd like to achieve is to use on ICS the ActionBarSherlockCompat instead of the ActionBarSherlockNative. Anyway the result should be the same and in this way I would be able to force the overflow menu.
I tried playing a bit with the source code and I removed the line "registerImplementation(ActionBarSherlockNative.class);" from ActionBarSherlock.java...and it kind of works...on ICS I get the overflow menu, but I see two action bars (native + compat). I will probably also have to change the layouts used on ICS and pick the NoActionBar stuff...mmm. Little help? :)

**Comment by SimonVT** [comment]
Remember that users with those devices are used to having a menu button. They are NOT used to having an overflow menu. By forcing this you are giving users an inconsistent experience, which is bad.
Imo it was a mistake to ever include ForceOverflow.

**Comment by yuvidroid** [comment]
That's true, those users are used to have an hardware menu button. But still, when they would press it (even when the overflow menu icon is present) the menu would appear, so I don't think it's so bad.
The reason I really want to force the overflow menu button is because I want my apps to look the same on all devices, so that when I write tutorials, make videos, help pages, screenshots and whatnot I can always say e.g. "press the menu icon", instead of saying "if your phone has a menu button press that, otherwise press that other thing, but if you run Android 2.x then do that...oh but with Android 3.x you should do that other thing..".

**Comment by SimonVT** [comment]
I'd take consistency over saving a line of text in some tutorial most of your users probably wont read anyway.

**Comment by yuvidroid** [comment]
I don't agree...many of my users do read tutorials and I prefer keeping that part clean and consistent.

**Comment by yuvidroid** [comment]
Jake, do you have any advice regarding my previous comment? (https://github.com/JakeWharton/ActionBarSherlock/issues/239#issuecomment-5807766)

Thank you!

**Comment by JakeWharton** [comment]
I don't necessarily have any advice. We debated this a lot for our apps at Square and ultimately decided that forcing the overflow was a mistake. We are now adhering to whatever the platform default is.

I agree with @SimonVT that including force overflow was a mistake since it's not supported on ICS. If Android revisits the option in the future then I will to. Until then I'm not an advocate of using the feature.

**Comment by RawPhunky** [comment]
Google+ app has overflow item (on device with hardware menu button).
Tho, it seems that it's just a menu item with sub items. Maybe it's a good way to fake it.

**Comment by SimonVT** [comment]
Google+ doesn't use the native ActionBar.
