### ISSUE TITLE
TargetSDK is different from project.properties

### ISSUE THREAD

**Issue by iNoles** [JakeWharton/ActionBarSherlock#242]
in AndroidMainfest.xml

`xml <uses-sdk
        android:minSdkVersion="7"
        android:targetSdkVersion="15" />`

and project.properties is target=android-14

is it is 15 or 14?

**Comment by JakeWharton** [comment]
Compilation is set to Android 4.0 because there are no 4.0.3 artifacts in Maven Central. I try to set the compilation requirement as low as possible while still supporting everything we need for the library. Only when there is an essential feature of a future API level will I bump it up. This way you're not required to always compile with the latest if, for some reason, you don't want to.

The `targetSdkVersion` itself is actually nearly useless. We could set it as low as 11 if we wanted in the sample apps and get rid of it altogether in the library itself. I always set it to the newest API possible so that fancy new things like hardware acceleration and the like is enabled by default. If API 16 comes out with no changes to the action bar API I'd bump it up without raising the compilation target just in case it enables some fancy new thing. The documentation will state, though, that the minimum target to be specified is 11 but it's recommended that you use 14 or higher (to enable hardware acceleration by default).
