### ISSUE TITLE
Home icon not working on 2.x

### ISSUE THREAD

**Issue by nelenkov** [JakeWharton/ActionBarSherlock#257]
It seems onOptionsItemSelected() is not called when clicking the home icon on 2.x. It does work though if  you call setDisplayHomeAsUpEnabled(true) when starting the activity. Also works as expected on ICS (native action bar). I thought it was a problem with my styles, but same result with 'stock' @style/Theme.Sherlock. 

Using Beta 6.

**Comment by JakeWharton** [comment]
The home icon is disabled by default if you target API 14 or greater and must be enabled with the method call as you mention. If you target a lower API (in our case only 11, 12, and 13 would be possible) it will be enabled by default.

In beta 6 pre-ICS was always disabled by default (rather than honoring the `targetSdkVersion`) but it has been fixed in the `4.0-wip` branch to match behaviors. If you'd like, you can download the latest version of the library from that branch and it will still work with the support-lib plugin from beta6 to try.

**Comment by nelenkov** [comment]
Ah, here it is:

https://github.com/JakeWharton/ActionBarSherlock/commit/a309e446872b76ff1da6f90e45bf13eb76083b2a

Works fine with latest 4.0-wip, I'll switch to wip until 4.0 is released. Long time no Maven, but it's all set up now.
