### ISSUE TITLE
WVGA854 (480x854) - overflow item size incorrect with ForceOverflow theme and showAsAction="always|withText"

### ISSUE THREAD

**Issue by jgilfelt** [JakeWharton/ActionBarSherlock#264]
Very much an edge case here. It seems like when using a `ForceOverflow` theme and having action item(s) set to `android:showAsAction="always|withText"` on a normal-long screen, if there is enough room to show `withText` items then the overflow action item will appear with excessive padding to the right. The sizing seems fine on normal (not long) screen configurations.

Screenshot (2.3): http://twitpic.com/8jvf9l/full

**Comment by JakeWharton** [comment]
Can you see if you can modify the [ForcedOverflowItem](https://github.com/JakeWharton/ActionBarSherlock/blob/4.0-wip/samples/demos/src/com/actionbarsherlock/sample/demos/ForcedOverflowItem.java#files) demo so that the error shows? I tried a bunch of combinations of `always`/`ifRoom` and `withText` with its 6 items and was unable to reproduce on either 2.1 or 2.3.3 with HVGA and WVGA854.

**Comment by jgilfelt** [comment]
Well I was able to reproduce it with the demo by just having a single `always|withText` item, however it seems like this is just a quirk with the device I am using to test with (a Sony Ericsson X10), as it is fine on the emulator with the same spec AVD: http://twitpic.com/8jwl1f/full

Closing as a non-issue.
