### ISSUE TITLE
titleTextStyle needs to be added to the "drop the android prefix list"

### ISSUE THREAD

**Issue by Esteth** [JakeWharton/ActionBarSherlock#27]
On http://actionbarsherlock.com/theming.html no mention is made of the titleTextStyle attribute, which must have the android: prefix dropped for actionBarSherlock to recognise and use.

**Comment by JakeWharton** [comment]
This is actually a bug too rather than just an omission on the documentation. The pre-3.0 action bar will honor the attribute but the native 3.0+ one does not map it back to the native `android:titleTextStyle`. The same goes for every other attribute defined in the action bar or action mode style.

Glaring omission on my part!

**Comment by JakeWharton** [comment]
This is fixed (rather, worked around) in the `dev` branch. Read the change log for more info. Will be released with 3.1 in the coming few days.
