### ISSUE TITLE
@Override annotation used wrongly

### ISSUE THREAD

**Issue by schildbach** [JakeWharton/ActionBarSherlock#28]
In Java5, @Override is only used for overriding methods in classes, not for interfaces.

Thus, Eclipse 3.6 shows errors all over the place. And I have not found another workaround than setting the whole project to Java6, which it surely isn't.

**Comment by ChrisSmith** [comment]
What is wrong with using the Java6 compiler? The @Override annotation is allowed on interfaces in 6.

**Comment by schildbach** [comment]
I was under the impression that ActionBarSherlock is an Android project, which is currently locked to Java5. If you require Java6, you should at least make that very clear in the docs. And even better, if you import the project as an existing project like I did, Java6 should be pre-selected.

**Comment by JakeWharton** [comment]
Can you cite where it is said that Java 5 is to be used? Since Android 2.3 the SDK requires Java 6, I only assumed that by extension applications written for API levels equal to or later than that should follow suit. If that is not the case I will make the switch but I am inclined to target the latest version by default which is why the project is such.

I'll update the documentation regardless once a definitive answer is determined.

**Comment by JakeWharton** [comment]
The [Android requirements page](http://developer.android.com/sdk/requirements.html) states that the JDK 5 or 6 is appropriate. I'd like to use the latter because things like `@Override`s afford additional compile-time checks to make sure i'm actually overriding the desired method.

I will note on the documentation.
