### ISSUE TITLE
Howto always use ActionBarSherlock implementation?

### ISSUE THREAD

**Issue by antonj** [JakeWharton/ActionBarSherlock#282]
How do I make sure that ActionBarSherlock's implementation is always used?

 For example if I override and customize `abs__screen_action_bar.xml` or `abs__action_bar_title_item.xml` in my project. Can I force these layouts to be used on all devices including ICS?

Many thanks for ActionBarSherlock btw, it's awesome!

**Comment by JakeWharton** [comment]
The API for doing this is not stable which is why I commented out the sample at the last minute before RC1. I want to use a callback mechanism rather than an argument to the superclass constructor so that you have a chance to perform some logic about the device first.

If you want access to it now, check out the "lost" sample for it [here](https://github.com/JakeWharton/ActionBarSherlock/blob/4.0-wip/samples/demos/src/com/actionbarsherlock/sample/demos/ForcedCompatImpl.java#L25-27). Just be warned that you'll likely have to adapt to whatever I change it to on a future release candidate (or the final release). There will be a proper public sample to follow then, though.

**Comment by antonj** [comment]
Thanks, I'll try that for now

**Comment by antonj** [comment]
The sample is lost again. Are there any news on this?

**Comment by JakeWharton** [comment]
``` java
ActionBarSherlock.unregisterImplementation(ActionBarSherlockNative.class)
```

No guarantees that it will work, though.

**Comment by Sleepybear** [comment]
I know it has issues on ICS if you just force it to use the Compat implementation. I had started to try and iron out the issues but didn't get to them all by the time I got busy with other things.

Theming was definitely an issue, because Theme.Sherlock.\* inherit from ICS Holo themes and so the compat implementation has issues accessing the properties. I can't remember what else was a problem

**Comment by antonj** [comment]
I've only tried this on Samsung Galaxy Nexus, but this works great with no issues as long as you remove the `values-v11` and `values-v14` folders from ABS-library.

This is really good for heavily customized ActionBars, no need to handle the native ActionBar anymore. Long live ActionBarSherlock!

**Comment by Sleepybear** [comment]
That would definitely solve the Theming issues, but you may want to just
remove the abs__styles.xml and abs__themes.xml, I can't remember if there
were some other dimens.xml or things in there off the top of my head.

On Fri, Apr 27, 2012 at 1:29 AM, Anton Johansson <
reply@reply.github.com

**Comment by Sleepybear** [comment]
Seems like I remembered wrong, and there is only theme/style stuff in the values-v11/14 dirs. The dimens and other things are handled by screen size resource quantifiers. Will have to remember that in the future.
