### ISSUE TITLE
"Done" text in ActionMode on Light.DarkActionBar using wrong color

### ISSUE THREAD

**Issue by BeowulfBjornson** [JakeWharton/ActionBarSherlock#302]
It is using the same color from when using the Light theme, so it is technically unreadable. This is on 4.0, but the title was already big enough haha I've tested on 3.2 emulator and there the Done text isn't even shown.

It works fine on both Theme.Sherlock and Theme.Sherlock.Light

Image for clarification:

![screenshot](http://i.imgur.com/hoMxA.png)

**Comment by Sleepybear** [comment]
Just updated my acer A500 to ICS and made a quick test app not using the ABS library and guess what... same shit happens, so this is a bug in the ICS Source. Going to work on a work around for ABS library. 

Only took me 3 hours of digging through styles/themes to decide to make a native test app...

**Comment by Sleepybear** [comment]
http://code.google.com/p/android/issues/detail?id=26008
Opened bug report on b.android.com

**Comment by Sleepybear** [comment]
Can fix it on <4.0 by using style attributes, either by adding a new one or changing what attribute the abs__action_mode_close_item.xml references, but since 4.0+ uses native action bar, can't fix it. If you override the textAppearanceSmall attribute to be the light color, then all the text in the content will be un-readable.

Jake, got any thoughts?
