### ISSUE TITLE
MenuInflater does not respect XML attributes "actionLayout" and "actionViewClass"

### ISSUE THREAD

**Issue by drsoran** [JakeWharton/ActionBarSherlock#32]
Release 3.0.2

When inflating a menu defined as XML resource, using _android.support.v4.view.MenuInflater_, the XML tags "actionLayout" and "actionViewClass" are ignored.

Don't know if this is still unsupported cause the code is commented in _android.support.v4.view.MenuInflater:383_ and _android.support.v4.view.MenuInflater:394_

**Comment by JakeWharton** [comment]
I'd like to hopefully get the opinion of as many other users as well on this to determine the best course of action.

Thus far this has been by design. As you noted, the support was implemented and then commented out. I chose to do this for two reasons.
1. If the custom action bar was shown then there is a high probability the application is running on a phone with a relatively small screen. The screen real estate does not usually exist for the type of views which are normally associated with these two attributes.
2. Both of these attributes override the specified title and icon associated with the menu item. This allows for an automatic yet graceful degredation of functionality.
   
   For example, in a project I am working on I utilize Honeycomb's new search widget but I also specify an icon.
   
   ``` xml
   <item
       android:id="@+id/menu_search"
       android:icon="@drawable/ic_menu_search_holo_light"
       android:title="@string/search"
       android:showAsAction="always"
       android:actionViewClass="android.widget.SearchView" />
   ```
   
   This will show the widget on Android 3.0+ and allow for its in-place interaction but when run on pre-3.0 only the icon will show and the `onOptionsItemSelected` event will fire allowing me to use the search popup.

Is this the correct functionality? I'm not so sure.

The library was built to offer as much support as possible for the action bar, the current implementation and API of which has been clearly designed for large-screen devices, on devices with small screens and previous version of Android. Small assumptions have been made to allow for as much out-of-the-box functionality as possible (e.g., not displaying action item text unless explicitly requested to, regardless of the `withText` flag). The scope of this issue may fall outside that of a small assumption.

As a counter argument, here are two ways the exact same functionality I describe above can be achieved if we choose to enable these features.
1. A custom view can appropriately render itself based off of the screen configuration it detects from its `Context` instance. On non-`xlarge` screens it could choose to only display itself as an icon, text, or as a small view.
2. After menu inflation (or during creation from code) the custom view could be cleared when the device is not approprite.
   
   ``` java
   if (Build.VERSION.SDK_INT < Build.VERSION_CODES.HONEYCOMB) {
       menu.findItem(R.id.menu_search).setCustomView(null);
   }
   ```

I'd like to get your thoughts on the matter and hopefully other users who also watch the project and utilize the library can also voice their opinions on this matter.

**Comment by drsoran** [comment]
I can follow your thoughts why to comment out the code. But every user of your library does this by full intention. And I think everybody does this by supporting phones and tablets at the same. It's not like tweaking a phone to be able to run 3.0+ apps which were designed for tablets only.

So I think the people are aware of the fact that they cannot provide tablet-only ActionViews for both worlds. Speaking for me, I would favor to re-enable the attributes. Android provides a good functionality to switch resources by configuration attributes like the screen size. By providing different ActionView layouts for different configurations is a clean and straight way to handle this.

**Comment by JakeWharton** [comment]
I agree. If you're using this library, you are in it all the way. The burden should not be placed on the library to decide what is displayed and how in this case. I will enable them for the forthcoming release.

I hadn't been thinking about using resource folders to differentiate between the API levels. This also makes me question my choice of hiding the action item text by default as well. The same could be done with resource filtering for menu XML. What are your thoughts on that?

**Comment by drsoran** [comment]
I always prefer the resource facility from Android. It's a good separation of concerns. It separates the logic from the visualization. And why to re-implement the decision how to display something if this is already done by the framework. Of course I cannot judge for your special case cause I simply don't know your implementation. I don't know if this fits to some special cases which cannot be handled by a simple XML resource file.

Off topic: I hope I don't bomb you too much with issues. If think this helps to improve the library and you alone cannot think of every special case someone else will use. Keep up the good work!

**Comment by JakeWharton** [comment]
No, keep them coming. I'm glad to see people actually using the library and finding out oddities and errors that exist. I can only think of and test so many configurations. Plus your bug reports are extremely descriptive allowing me to understand exactly what your problem is and half the time you even tell me where the problem exists in the library itself.
