### ISSUE TITLE
Evaluate Supporting Batch Contexual Actions

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#347]
I had never known this existed...

http://developer.android.com/guide/topics/ui/menus.html#CABforListView

Definitely a non-trivial fix that will not be able to use the same API. It looks like this functionality is built in to `ListView` itself. The only viable option maybe to extend to a `SherlockListView` (but then it can't be used out-of-the-box with `SherlockListActivity`/`SherlockListFragment`). Will need further investigation.

**Comment by timroes** [comment]
I would consider this a really important topic, since ListViews are imho one of the most important usages of contextual action bars. We implemented a ListView, that does nearly what the native android implementation does. You can find it here: https://github.com/DokuWikiMobile/dokuwikimobile/blob/alpha/src/org/dokuwikimobile/ui/view/ABSListView.java

I am not so much into the code of ActionBarSherlock, but I guess this code could perhaps be a help for an implementation in ActionBarSherlock. The javadoc shows the usage of the class and some differences to the native android implementation. 

For an example on the usage, this class https://github.com/DokuWikiMobile/dokuwikimobile/blob/alpha/src/org/dokuwikimobile/ui/activity/ChooserActivity.java might help.

I really hope this issue will soon be fixed in ActionBarSherlock :-)

**Comment by JakeWharton** [comment]
From @mrenouf: https://snipt.net/tweakt/sherlocklistviewjava/
