### ISSUE TITLE
Dialog Box Initialize Through Code

### ISSUE THREAD

**Issue by grimmdev** [JakeWharton/ActionBarSherlock#375]
I sifted through each of the samples and however you state in the dialog box content that it can be called or created through code, however I don't see any implementation of it or documentation on it.

**Comment by JakeWharton** [comment]
The dialog in the samples is actually a themed activity and not a true dialog. Perhaps I should clarify that in its name.

The problem is that you cannot set an activity's theme in the code when it is to be displayed as a dialog. You lose the cool translucent effect of the background.

If you're creating a dialog through code you should use the normal dialog creation mechanism: a `DialogFragment` or an `AlertDialog`.

**Comment by grimmdev** [comment]
i see what you mean now, i already understand the built in AlertDialog and DialogFragment was just curious what you ment directly. i loved the themed dialog which is why I asked,thanks for clerifying and explaining!
