### ISSUE TITLE
ICS blue showing on froyo

### ISSUE THREAD

**Issue by qbproger** [JakeWharton/ActionBarSherlock#382]
I wanted to make my app backward compatible the whole way back to froyo.  I loaded up ABS in an emulator, and saw that it had the ActionBar underlined with what appeared to be ICS blue.  What are your thoughts on this?

![screenshot](https://i.minus.com/izVYHa3lP3VoT.png)

**Comment by JakeWharton** [comment]
The library provides a normalized look and feel across all platforms it supports. It is up to you to customize to create a branding and experience within your application. There are no docs or guidelines which discuss how an action bar should be presented in functionality or style on pre-Honeycomb so it is up to your to make it your own.

I do NOT recommend people use an exact Holo look in an application. It is pretty simple to customize a theme to create a simple unique look. I will, however, recommend people take the assets from ICS (e.g., button styles, edit text styles) and customize them rather than starting from scratch.

If you have any more questions or thoughts please post on our forum (http://abs.io/forum) and I'll be happy to discuss further.
