### ISSUE TITLE
NullPointerException in onRestoreInstanceState

### ISSUE THREAD

**Issue by albnok** [JakeWharton/ActionBarSherlock#448]
SwiperActivity below, extends SherlockFragmentActivity from the ActionBarSherlock 4.0.2 library. I can only get this after loading loads of different apps, then switching back, on an Asus Eee Pad Transformer TF101 on ICS 4.0.3 OTA, as well as the Galaxy Nexus on ICS 4.0.4 OTA. I'm not sure if this is obviously an ICS 4.0.3 bug (it appears to match up with ICS source code herehttp://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.0.3_r1/com/android/internal/policy/impl/PhoneWindow.java#PhoneWindow.getPanelState%28int%2Cboolean%29).

I also get this on ActionBarSherlock 4.0.0 and 4.0.1.

I am not overriding onRestoreInstanceState or any of the instances or states.

(I also log the first line of each overridden Activity method e.g. "SwiperAct.onCreate 0" and at the end, "SwiperAct.onCreate 99", to try to pinpoint which method causes this. I log onResume as well so I know that this bug happens after onCreate and before onResume.)

04-16 14:30:57.710: D/dalvikvm(667): GC_CONCURRENT freed 2692K, 71% free 8750K/30023K, paused 2ms+4ms
04-16 14:30:58.140: D/dalvikvm(667): GC_CONCURRENT freed 120K, 69% free 9362K/30023K, paused 3ms+4ms
04-16 14:30:58.480: D/dalvikvm(667): GC_CONCURRENT freed 16K, 67% free 10207K/30023K, paused 4ms+5ms
04-16 14:31:00.700: D/dalvikvm(18313): Late-enabling CheckJNI
04-16 14:31:00.700: I/ActivityManager(557): Start proc com.company.appname for activity com.company.appname/.SwiperActivity: pid=18313 uid=10011 gids={3003, 1015}
04-16 14:31:00.720: D/WindowManager(557): readLidState, sw:1
04-16 14:31:00.720: D/WindowManager(557): adjustConfigurationLw, config:{1.0 0mcc0mnc (no locale) layoutdir=0 sw800dp w1280dp h752dp xlrg land ?uimode ?night finger qwerty/v/v -nav/v} mLidOpen:1 mHasDockFeature:true mHasHallSensorFeature:true config.hardKeyboardHidden:1
04-16 14:31:00.730: D/OpenGLRenderer(18274): Flushing caches (mode 1)
04-16 14:31:00.730: D/dalvikvm(18313): Debugger has detached; object registry had 1 entries
04-16 14:31:00.900: D/OpenGLRenderer(18274): Flushing caches (mode 0)
04-16 14:31:00.950: D/OpenGLRenderer(667): Flushing caches (mode 0)
04-16 14:31:00.970: E/SwiperAct.onCreate 0(18313): starting...
04-16 14:31:00.980: D/SwiperAct.onSingleUse 0(18313): starting...
04-16 14:31:01.050: D/SQLiteUtil(18313): create DatabaseOpenHelper instance
04-16 14:31:01.050: D/SQLiteUtil(18313): create DatabaseOpenHelper instance
04-16 14:31:01.080: V/SQLiteOpenHelper(18313): onOpen()
04-16 14:31:01.100: V/SQLiteOpenHelper(18313): onOpen()
04-16 14:31:01.100: D/SwiperAct.onSingleUse 99(18313): ending...
04-16 14:31:01.120: D/dalvikvm(18313): GC_CONCURRENT freed 209K, 5% free 6728K/7047K, paused 4ms+2ms
04-16 14:31:01.190: E/SwiperAct.onCreate 99(18313): ending...
04-16 14:31:01.200: D/AndroidRuntime(18313): Shutting down VM
04-16 14:31:01.200: W/dalvikvm(18313): threadid=1: thread exiting with uncaught exception (group=0x40a7b1f8)
04-16 14:31:01.200: E/AndroidRuntime(18313): FATAL EXCEPTION: main
04-16 14:31:01.200: E/AndroidRuntime(18313): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.appname/com.company.appname.SwiperActivity}: java.lang.NullPointerException
04-16 14:31:01.200: E/AndroidRuntime(18313):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1956)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at android.app.ActivityThread.access$600(ActivityThread.java:123)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at android.os.Handler.dispatchMessage(Handler.java:99)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at android.os.Looper.loop(Looper.java:137)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at android.app.ActivityThread.main(ActivityThread.java:4424)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at java.lang.reflect.Method.invokeNative(Native Method)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at java.lang.reflect.Method.invoke(Method.java:511)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at dalvik.system.NativeStart.main(Native Method)
04-16 14:31:01.200: E/AndroidRuntime(18313): Caused by: java.lang.NullPointerException
04-16 14:31:01.200: E/AndroidRuntime(18313):    at com.android.internal.policy.impl.PhoneWindow$PanelFeatureState.onRestoreInstanceState(PhoneWindow.java:3341)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at com.android.internal.policy.impl.PhoneWindow.restorePanelState(PhoneWindow.java:1663)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1619)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at android.app.Activity.onRestoreInstanceState(Activity.java:906)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at android.app.Activity.performRestoreInstanceState(Activity.java:878)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1100)
04-16 14:31:01.200: E/AndroidRuntime(18313):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1934)
04-16 14:31:01.200: E/AndroidRuntime(18313):    ... 11 more
04-16 14:31:01.200: W/ActivityManager(557):   Force finishing activity com.company.appname/.SwiperActivity
04-16 14:31:01.500: D/dalvikvm(18313): GC_CONCURRENT freed 177K, 4% free 7027K/7303K, paused 1ms+3ms
04-16 14:31:01.610: D/dalvikvm(18313): GC_CONCURRENT freed 114K, 3% free 7455K/7623K, paused 6ms+3ms
04-16 14:31:01.740: D/dalvikvm(18313): GC_CONCURRENT freed 117K, 3% free 7900K/8071K, paused 3ms+3ms
04-16 14:31:01.750: D/WindowManager(557): readLidState, sw:1
04-16 14:31:01.750: D/WindowManager(557): adjustConfigurationLw, config:{1.0 0mcc0mnc (no locale) layoutdir=0 sw800dp w1280dp h752dp xlrg land ?uimode ?night finger qwerty/v/v -nav/v} mLidOpen:1 mHasDockFeature:true mHasHallSensorFeature:true config.hardKeyboardHidden:1
04-16 14:31:01.750: W/ActivityManager(557): Activity pause timeout for ActivityRecord{41568e50 com.company.appname/.SwiperActivity}

Is this an Android bug, or could it be ActionBarSherlock's, if it overrides states? I don't even know where to look, if it is my app's bug.

**Comment by willlunniss** [comment]
I've been looking into the same problem, however, I've got about as far as you for working it out. I have recieved crash reports from useres with ICS 4.0.3 and 4.0.4 on a mix of devices and have been waiting to hear back from them to get more details as I wasn't sure which ROM they were using. I don't have an ICS device, so my next step was to see if it happens in the emulator. Again it is in an activity that doesn't use onRestoreInstanceState.

**Comment by iNoles** [comment]
It is hard to find problem without your app source code.

**Comment by willlunniss** [comment]
I'll try to put together as small as example as possiable at the wekeend. However the problem is, the exception doesn't go through any of my code, so i'll have to work out what I'm using, that triggers it.

**Comment by willlunniss** [comment]
I tried to put together an example, but I cannot get it to happen in the emulator (4.0.3). I start the app, then load lots of other apps until I get the "ActivityManager No longer want package" message, then start the app again, but it loads fine without any exceptions. I also tried rotating and then starting it again.

**Comment by SimonVT** [comment]
This doesn't seem related to ABS at all, judging from where it's crashing. ABS does not override or touch any saved state.

**Comment by albnok** [comment]
Hmmm should this be closed or kept open? Given that this is the only place which has any reply.

I've cross-posted here:

http://stackoverflow.com/questions/10205306/nullpointerexception-in-onrestoreinstancestate
https://groups.google.com/forum/?fromgroups#!topic/android-developers/FaVG2seV7lM

Also, I have found a way to instantly trigger this instead of eventually pushing the app out of memory - in Settings - Developer options - tick "Don't keep activities".

Run the app, press Home, then hit the Task Switcher and load your app again. It should immediately cause the NullPointerException.

**Comment by JakeWharton** [comment]
When running on ICS ActionBarSherlock does almost nothing but pass things along to the native action bar and menu classes. Without a sample to reliably reproduce the bug there's no way to even debug what's going on. It's highly unlikely that the behavior is related to this library.

If you find further proof that it is, however, feel free to update the bug (with a sample) and I'll re-open.

**Comment by KarthickCk** [comment]
I got this error while im using ActionBarActivity in AppCompact

AndroidRuntime(23268): FATAL EXCEPTION: main
E/AndroidRuntime(23268): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.adventnet.webmon.android/com.adventnet.webmon.android.NavigationDrawerBaseActivity}: java.lang.NullPointerException
E/AndroidRuntime(23268):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2110)
E/AndroidRuntime(23268):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
E/AndroidRuntime(23268):    at android.app.ActivityThread.access$700(ActivityThread.java:140)
E/AndroidRuntime(23268):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
E/AndroidRuntime(23268):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23268):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(23268):    at android.app.ActivityThread.main(ActivityThread.java:4921)
E/AndroidRuntime(23268):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(23268):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(23268):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
E/AndroidRuntime(23268):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
E/AndroidRuntime(23268):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(23268): Caused by: java.lang.NullPointerException
E/AndroidRuntime(23268):    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2831)
E/AndroidRuntime(23268):    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2832)
E/AndroidRuntime(23268):    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2832)
E/AndroidRuntime(23268):    at android.view.View.restoreHierarchyState(View.java:12206)
E/AndroidRuntime(23268):    at android.support.v4.app.Fragment.restoreViewState(Fragment.java:425)
E/AndroidRuntime(23268):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
E/AndroidRuntime(23268):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
E/AndroidRuntime(23268):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
E/AndroidRuntime(23268):    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1877)
E/AndroidRuntime(23268):    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
E/AndroidRuntime(23268):    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1178)
E/AndroidRuntime(23268):    at android.app.Activity.performStart(Activity.java:5216)
E/AndroidRuntime(23268):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2083)
E/AndroidRuntime(23268):    ... 11 more
D/WindowManager( 2104): mInputFocus is not null.
