### ISSUE TITLE
Investigate ActivityUnitTestCase Usage

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#454]
`getSupportActionBar()` always seems to return `null` apparently...

**Comment by JakeWharton** [comment]
We use instrumentation tests at Square and both of our apps allow this fine.

**Comment by jobi** [comment]
Hmm how do you do it? I getSupportActionBar returns null here

**Comment by fidanov** [comment]
I have another problem with ActivityUnitTestCase on older Android versions (2.3 or older). It tells me that a Sherlock theme is not set, which is not true because when I run the app in normal mode everything is just fine and I have set such a theme in the manifest.

It happens because ActivityUnitTestCase does not respect the theme set in the manifest file (and probably other values set there).

The solution for me was to add this to my SetUp method. 

``` java
ContextThemeWrapper context = new ContextThemeWrapper(getInstrumentation().getTargetContext(), com.example.app.R.style.MyTheme);
setActivityContext(context);
```

However, this does not solve the getSupportActionBar() returns null problem. It just helps a little bit when using ActivityUnitTestCase.

**Comment by orrc** [comment]
@fidanov I've seen that problem several times before while writing tests for non-ActionBarSherlock apps, so I don't think it's an issue with this library.

It's a shame `ActivityUnitTestCase`s aren't supported though, as they're pretty simple to write and really fast to run.

**Comment by orrc** [comment]
So it looks like this is a property of `ActivityUnitTestCase`, rather than of ActionBarSherlock.

Calling either the native `getActionBar()` or ABS's `getSupportActionBar()` method causes the activity to initialise an action bar.  But in the call to [`Activity#initActionBar()`](https://github.com/android/platform_frameworks_base/blob/android-4.2_r1/core/java/android/app/Activity.java#L1863) it checks whether this Activity has a parent (i.e. `isChild()`), in which case an action bar shouldn't be added.

When `ActivityUnitTestCase` starts the activity under test it adds a mock parent, which means no action bar is ever created, which in turn causes the NPE.

**Comment by AlexBonel** [comment]
@orrc Good observation

There is also an issue associated with creating of component name in `ActivityUnitTestCase`'s `startActivity()` method described [here](http://code.google.com/p/android/issues/detail?id=22737)

**Comment by dabitdev** [comment]
What is JakeWharton saying with _We use instrumentation tests at Square and both of our apps allow this fine._
Square has only _Spoon_ to make test, is Spoon fixing the problem testing the ActionBar?

@orrc I agree with you I have the same problem.

@alexBonel I fixed the problem with the componentName addign a setter to the ActivityUnitTestCase, setPackageName(String name), and from the unit test call this before starting the activity 

`setPackageName(getInstrumentation().getTargetContext().getApplicationInfo().packageName);`

`ComponentName cn = new ComponentName(packageString, mActivityClass.getName());`
