### ISSUE TITLE
Shareactionprovider does nothing if triggered from inside an Optionsmenu

### ISSUE THREAD

**Issue by jleidgens** [JakeWharton/ActionBarSherlock#455]
The ShareActionProvider does nothing if it is hidden in the Optionsmenu of a Device with Android 2.2 (tested with first 7" Galaxy Tab). 

Normally the action provider should open up a pop menu with options to share the intent. It seems that this is not possible from the options menu. Maybe a fallback would be to just start the share Intent to invoke the standard action chooser.

**Comment by navarr** [comment]
A work around would be to set up the XML so that ShareActionProvider is always shown in the action bar (taking precedence over other action icons)

**Comment by Sleepybear** [comment]
That is a bit odd as I have a custom ActionProvider inside a submenu in my app that works amazingly well, even on pre 3.0. Could be something with the ShareActionPrivder code. I know it's a weird setup when it's in a submenu...

**Comment by Sleepybear** [comment]
Do you happen to have a sample apk and/or source code?

**Comment by JakeWharton** [comment]
I'm thinking we need to add a 'bugs' module where we can add demos which exhibit all the bugs that are left to fix.

**Comment by JakeWharton** [comment]
There's a fundamental limitation on how the `MenuBuilder` dispatches callbacks that prevents us from handling this gracefully. There are three possible ways to handle this:
1. On pre-Honeycomb force the action item into the overflow and just call `startActivity` in the `onOptionsItemSelected` callback _(remember to check the API level in the callback too)_.
2. On pre-Honeycomb force the action item onto the action bar and behavior will be correct.
3. On pre-Honeycomb use a force overflow theme and behavior wil be correct.

I don't think I'll ever be able to truly support this operating in the appropriate way since the changes have far too large an impact on how the menu works.
