### ISSUE TITLE
ActionBar remains white in `PreferenceActivity` while `Theme.Sherlock` is set

### ISSUE THREAD

**Issue by zhen9ao** [JakeWharton/ActionBarSherlock#499]
This can only reproduced in my phone, which has the ROM of MIUI version 2.3.7 (not the stock ROM). I tested it on emulator 2.3.3 and 4.0.3, both work correct.

**Comment by zhen9ao** [comment]
It looks like this in my ROM:

Default: http://d.pr/i/yK3b
Light: http://d.pr/i/cvHs
Light(Dark ActionBar): http://d.pr/i/YkX2

**Comment by JakeWharton** [comment]
The action bar is transparent by default. Use `Widget.Sherlock.ActionBar.Solid` for an opaque one.

**Comment by zhen9ao** [comment]
It's what it looks like of the `sample-demo` app of ActionBarSherlock, the `Preferences` activity.

**Comment by JakeWharton** [comment]
`Theme.Sherlock` extends from `Theme` on pre-Android 3.0. Your ROM has modified the default styling of a preference activity from being dark to light which is very non-standard (and would probably be a violation of [the CDD](http://source.android.com/compatibility/index.html) if it was official). `Theme.Sherlock` operates under the assumption that the background will be dark which is why the action bar background is transparent.
