### ISSUE TITLE
Split SherlockFragmentActivity into interface and implementation

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#515]
I have to use an Activity base class that I can't change and tried to extend it in a way as it is done with SherlockMapActivity. Unfortunately, attaching a Fragment to the customised Activity results in an IllegalStateException. A SherlockFragment accepts only SherlockFragmentActivities as its container.

How about having an interface SherlockFragmentActivity, and a concrete sub-class BaseSherlockFragmentActivity? onAttach() and getSherlockActivity() in SherlockFragment could then accept/return anything that implements the interface.

**Comment by JakeWharton** [comment]
The reason the library fragments only accept `SherlockFragmentActivity` as their parent activity is because they are tightly coupled with the menu callbacks and none of the other base activities provide the fragment support for the support library. There is also the `Watson` class which lives inside the support library package in order to gain access to package protected members of the `FragmentActivity` class. If you need to create a heavy customization like this I suggest you either modify the library in a fork directly or you provide your own fragment base classes to coincide with your new base activity.

Also, an interface cannot be used since you can't use an instance of it as a context or activity despite knowing that it always would be an instance of one. This was a huge problem with ABS v3 and is something I will do everything in my power to avoid.
