### ISSUE TITLE
please provide jar file for abs

### ISSUE THREAD

**Issue by mecid** [JakeWharton/ActionBarSherlock#538]

**Comment by jameswald** [comment]
ABS must be compiled as a library project.  http://actionbarsherlock.com/faq.html

Why is ActionBarSherlock a library project whereas the original compatibility library is only a .jar?

The custom action bar implementation within ActionBarSherlock relies on styles, themes, layouts, and drawables in order to display properly. Due to the limitations of Android and .jar files, this currently can not be accomplished any other way.

**Comment by mecid** [comment]
thanks man
