### ISSUE TITLE
Templates for new projects/activites

### ISSUE THREAD

**Issue by jmgrosen** [JakeWharton/ActionBarSherlock#552]
The ADK 20.0.0 introduced a way to have templates; the default ones are pretty simple, but mostly only for SDK version 14 or above, mainly because of the use of an action bar.

Could we re-implement the default templates using ActionBarSherlock? That would make it a lot easier to get started.

**Comment by JakeWharton** [comment]
This would be great for a user contribution since I don't use Eclipse (I'm assuming you mean the ADT Plugin introduced these). From my experience showing people the 'Demos' sample is usually enough to get them started.

**Comment by JakeWharton** [comment]
Going to close this since I don't use Eclipse and never plan to again. However, I still encourage someone to pick this up for new users as a third-party contribution. If it works I think it would be incredibly helpful as you say.

A possible limitation is that using ABS requires a library project which I'm not sure these templates would cover.
