### ISSUE TITLE
Collapsible EditText not restoring instance state on rotation

### ISSUE THREAD

**Issue by MichaelSims** [JakeWharton/ActionBarSherlock#566]
(**NOTE**:  (Mostly) minimal reproduction code here: https://github.com/MichaelSims/CollapsibleActionItemRotationTest/tree/action-bar-sherlock)

Observed on HTC Thunderbolt (2.3.4) using ActionBarSherlock version 4.1.0
##### Steps to reproduce
- Add a collapsible item to the action bar using `android:showAsAction="always|collapseActionView"` and `android:actionLayout` pointing to a layout file containing an EditText
- Expand the action item, enter some text into the EditText field.
- Rotate the device
##### Expected behavior

After rotation, the collapsed/expanded state should be restored, and the EditText action item should remain expanded.  State associated with the EditText (contents, cursor position, etc.) should be maintained.
##### Actual behavior

The collapsed/expanded state is reset, and the collapsible item is collapsed.  Upon expanding the item again, the state of the EditText is gone (empty).

Note that this behavior was also observed in the sample-demos app (Collapsible Action Items sample).  The framework implementation exhibits the expected behavior above on Asus Nexus 7" tablet running Android 4.1.1

Original google groups discussion: https://groups.google.com/forum/#!topic/actionbarsherlock/kZlRLtdZ_4E/discussion

**Comment by f4bo** [comment]
why this issue have been closed? I'm asking since it is already there in the ABS 4.2.0 : you put some test in a collapsible SearchView, you rotate the phone and then the text has gone and this is clearly an issue. The problem is in the SearchView class at line 1289 in the onActionViewExpanded method where the text is set to blank, while should have not. If you comment that line, the issue disappear. My only concern is: was there a real purpose to put such a command there?
