### ISSUE TITLE
Subtitle in ActionBar is not displayed

### ISSUE THREAD

**Issue by iNoles** [JakeWharton/ActionBarSherlock#57]
I use four tabs in ActionBar.

When I am testing it in Android 2.1 (API Level 7), getActivity().getSupportActionBar().setSubtitle("Something go here") but subtitle is not displayed. Maybe you forget to set it to Visibility to View.VISIBLE?

**Comment by JakeWharton** [comment]
Due to the limited space of a phone the title and subtitle are hidden when you are displaying tabs. I'm not sure how the forthcoming Ice Cream Sandwich version of Android will handle this but I'm not going to change the functionality until its sources are released.

You can place the tabs in the activity contents directly and style them to match the Holo theme using the following technique: https://gist.github.com/1126843. This will enable the display of both the title/subtitle and tabs. Since you only want this to happen on phones you would have to use two layouts (`layout` and `layout-v11`) and put some checks in the code but it could be managed.
