### ISSUE TITLE
Split action bar not working correctly in Android 4.1 (possibly due to configChanges)

### ISSUE THREAD

**Issue by cypherdare** [JakeWharton/ActionBarSherlock#687]
In a portrait activity, my buttons normally overflow to the split (bottom) action bar in Android 4.0.

The same apk on Android 4.1 shows the top action bar with no buttons, and the bottom action bar is missing. When I rotate to landscape, the action bar at the top has all the buttons, as expected.

Here's what's in the Activity's manifest portion:
                  android:label="@string/app_name_fs"
                  android:theme="@style/Theme.Sherlock"
                  android:launchMode="standard"
                  android:uiOptions="splitActionBarWhenNarrow"
                  android:configChanges="keyboard|keyboardHidden|orientation"

And I'm using this in onCreate():
                  requestWindowFeature(Window.FEATURE_ACTION_BAR_OVERLAY);
                  getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
                  getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);

**Comment by JakeWharton** [comment]
ActionBarSherlock does almost nothing on Android 4.0 and up. I would try making a sample application with the same configuration without using ActionBarSherlock and see if you get the same behavior. Otherwise, you'll have to provide a sample which demonstrates the bug you describe so I can easily reproduce it.
