### ISSUE TITLE
Feature request: PopupMenu

### ISSUE THREAD

**Issue by aperomsik** [JakeWharton/ActionBarSherlock#733]
For OI Shopping List  I backported PopupMenu from the ICS source code to run on Froyo. The result can be found here:

https://github.com/openintents/shoppinglist/blob/master/ShoppingList/src/org/openintents/shopping/ui/widget/backport/PopupMenu.java

Another project of interest to me, matburt/mobileorg-android, does use ActionBarSherlock and might benefit from PopupMenus in some spots. It seems like PopupMenu would make a natural addition to ActionBarSherlock. You seem to already have several of the classes on which it depends.

**Comment by Prototik** [comment]
You may use HoloEverywhere for holo-styled popupmenu and context menu. 
I don't think that popupmenu a part of actionbar.

**Comment by aperomsik** [comment]
Thanks for the pointer. Interesting that PopupMenu in HoloEverywhere depends only on ActionBarSherlock classes, not other HoloEverywhere classes. So if someone needs only PopupMenu, adding the whole HoloEverywhere might be overkill. Still, whatever ActionBarSherlock decides is fine-- just a suggestion.

**Comment by SimonVT** [comment]
ABS is just an ActionBar backport, it is not the place for general purpose backports of framework classes. Sure, a lot of functionality is backported, but it is only intended for use with the ActionBar. We can not guarantee it acts as its native counterpart for every use-case, since it's simply not the point.
If you wish to have a complete PopupMenu backport, create a repo. Have people use it and contribute.
