### ISSUE TITLE
addOnMenuVisibilityListener() doesn't work

### ISSUE THREAD

**Issue by Qubitium** [JakeWharton/ActionBarSherlock#763]
onMenuVisibilityChanged() is never triggered in the code below. Found this problem while debugging an app.

oncreate()....of a barebone SherlockActivity

``` java
ActionBar ab = getSupportActionBar();

//register actionbar hide/show listener
ab.addOnMenuVisibilityListener(new ActionBar.OnMenuVisibilityListener() {

    @Override
    public void onMenuVisibilityChanged(boolean isVisible) {
        // TODO Auto-generated method stub
        Log.e(TAG,"is this working?");
    }
});

ab.hide();

ab.show();

ab.hide();
```

**Comment by Qubitium** [comment]
Oops. Misread the doc. The listener is for menu of actionbar, not actionbar menu. Ahhhhhh...

**Comment by gryphon2411** [comment]
@diegomontoya, What was your solution for listening to any `ActionBar` visibility changes using either `hide()` or `show()`?

**EDIT**:
My current solution is to wrap, in each activity I want to handle `ActionBar` visibility changes, `getSupportActionBar().hide()` inside custom `hideSupportActionBar()` method and `getSupportActionBar().show()` inside custom `showSupportActionBar()` method, because the Android SDK doesn't provide neither straightforward listening to activity's `ActionBar` visibility changes nor overriding activity's `ActionBar` methods.
Consider the following code as an implementation for the above described solution:

```
private void showSupportActionBar() {
    // implement your code here before showing the ActionBar
 
    this.getSupportActionBar().show()
}

private void hideSupportActionBar() {
    // implement your code here before hiding the ActionBar
 
    this.getSupportActionBar().hide()
}
```
Use `showSupportActionBar()` and `hideSupportActionBar()` respectively as desired to get your code running.
