### ISSUE TITLE
Sherlock prefix unnecessary?

### ISSUE THREAD

**Issue by dskinner** [JakeWharton/ActionBarSherlock#802]
If the docs make the Sherlock prefix as unnecessary as it sounds, why not just name the Sherlock classes after the android counterparts, `Activity`, `FragmentActivity` and then one only needs to alter the import path (much like the google support library).

**Comment by JakeWharton** [comment]
The support library's `FragmentActivity` is named as such because it extends `Activity`. This is what inspired the `Sherlock`-prefixed activities.

At any rate it's far too late to change something like this now as it would require a major version bump. It's hard enough getting people to use the right classes as it stands now I can't imagine how hard it would be to try and tell beginners that they need to import `FragmentActivity` but the one from `com.actionbarsherlock.app.*` instead of `android.app.*`.

I agree that it would make things more elegant but it's simply not practical.

**Comment by dskinner** [comment]
thanks, I seem to forget that FragmentActivity is a v4 support lib only class for some reason but just shooting off a question more appropriate for twitter or the likes. Thanks for responding.
