### ISSUE TITLE
Update support library to r4

### ISSUE THREAD

**Issue by mernen** [JakeWharton/ActionBarSherlock#85]
Google released a new version of the support library (r4) with ICS, with numerous bugfixes.

**Comment by JakeWharton** [comment]
Already meld-ing against the `dev` branch. Going to be a week or so, though.

**Comment by enkoder** [comment]
First thing that I noticed after the upgrade is the Tab background images are stretched and look awful. If I run into any more problems, I will let you know. Thanks for your support Jake!

**Comment by johnpray** [comment]
enkoder, that stretching may be due to this bug with 9-patches in library projects in the ADT r14 preview: http://groups.google.com/group/adt-dev/browse_thread/thread/f1e1e801af487f36

Apparently it's been fixed in the final version but people are still having intermittent issues. See the last message for an apparent resolution ("clean/compile all, clean/compile the main project").

**Comment by JakeWharton** [comment]
This is done in the `dev` branch. Test 'em if you got 'em.

**Comment by JakeWharton** [comment]
Released as 3.4.0.
