### ISSUE TITLE
Make title text clickable

### ISSUE THREAD

**Issue by chicheng** [JakeWharton/ActionBarSherlock#881]
In Android 4.2.2, title text is also clickable while .setHomeButtonEnabled(true)

See first section on http://www.androidpolice.com/2013/02/15/getting-to-know-android-4-2-2-many-extremely-tiny-changes-and-an-androidhome-sighting/

**Comment by JakeWharton** [comment]
Dupe #832.

This won't be added because it would create inconsistency. ABS is a backport of the API 14 action bar. Any changes after those API levels will not be supported. If this was added it would only work on pre-ICS and 4.2.2+ which leaves 4.0, 4.1, and 4.2 with different behavior which is wrong.

**Comment by Zordid** [comment]
Actually, I think it's okay not to do this do stay consistent. But in my case, even on 4.2.2 it does not work due to me using a custom title. How can I get the clickable title behavior on 4.2.2 using ABS and a custom title? Any hint? Thx!
