### ISSUE TITLE
SDK 14 FragmentActivity testing issues

### ISSUE THREAD

**Issue by francisdb** [JakeWharton/ActionBarSherlock#89]
I still am not able to get my tests running correctly with the latests sdk release. I have the impression that only activities extending FragmentActivity cause problems.

2 Issues:
- ...Caused by: java.lang.NoClassDefFoundError: com.myapp.ui.MyFragmentActivity" causing the tests to not even start (ActivityInstrumentationTestCase2)
- When calling getActivity() I get this: java.lang.RuntimeException: Unable to resolve activity for: Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=com.myapp.ui/.MyFragmentMapActivity }

Both of these activities work perfectly fine outside of testing.

**Comment by atomusk** [comment]
Hi,

I have the same issue with my app crashing on smartphone after upgrading to ADT 14.

I get no issue with Honeycomb with actionbar displaying properly

Here is the crash  Obenkyo beeing my app and "main" beein my main FragmentActivity:
10-22 17:28:56.343: E/AndroidRuntime(13904): Caused by: java.lang.ClassNotFoundException: com.Obenkyo.Main in loader dalvik.system.PathClassLoader[/mnt/asec/com.Obenkyo-2/pkg.apk]
10-22 17:28:56.343: E/AndroidRuntime(13904):    at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:240)
10-22 17:28:56.343: E/AndroidRuntime(13904):    at java.lang.ClassLoader.loadClass(ClassLoader.java:551)

I have tried to update to the very last version and to reload the library without success.

Also, I have tried to compile the "shakespeare" sample working as expected on both smartphone and tablet. I will have to add features to this template to see where it could go wrong.

Regards.

**Comment by iNoles** [comment]
Real problem is java.lang.ClassNotFoundException: com.Obenkyo.Main

It is looking for Main under com.Obenkyo packages.

**Comment by atomusk** [comment]
"Main" beeing my Fragment activity class in my com.Obenkyo Package, I wonder why it is ... :/

**Comment by francisdb** [comment]
Will also try to reproduce this starting with a simple app

**Comment by francisdb** [comment]
This was an issue on my side, wrong package name in test constructor and library deployed twice in app/tests apk. Atomusk I don't think your issue is related to mine, might be better to create a new issue.

**Comment by atomusk** [comment]
You are right my issue is not related. I have to investigate further. I will open another ticket if I find an issue (sorry for the mistake)

**Comment by JakeWharton** [comment]
Hmm... I somehow disabled notifications for this issue. Didn't know that was possible if you were the repo owner. In any case, glad to see you guys managed to work out the issue!
