### ISSUE TITLE
Hiding 'Home Action' on Tabbed Actionbar

### ISSUE THREAD

**Issue by droidlooms** [JakeWharton/ActionBarSherlock#929]
Hiding 'Home Action' button/icon pushes the title bar down to the Tabs. I tried on my app and also see the same behavior on the samples. 

![image](https://f.cloud.github.com/assets/4357210/467506/03bc3aae-b67b-11e2-962b-54108109f9bf.png)

**Comment by JakeWharton** [comment]
This is the behavior of the native action bar as well on API 14 and 15. It was fixed in API 16, I think.

Since ABS emulates API 14 on previous API levels the behavior is expected. Your emulator looks to be either API 14 or 15 and thus is using the native action bar which is exhibiting this behavior.
