### ISSUE TITLE
Multiple tabs sliding issue

### ISSUE THREAD

**Issue by JJCodeTry** [JakeWharton/ActionBarSherlock#982]
I am using Sliding Menu and ActionBarSherlock in my application. 

I have multiple tabs (4-5) on the home page . The issue I am facing is related to 2.3 Android , when I click on any tab of home page and try to slide the tabs it works first time, but once you have scrolled to reach to last tab or any other tab then it is not easy to scroll back to the first tab. Instead the page slides and does not slide the tab.

One my Nexus 4  (Android 4.0) it works without any issues and is very smooth but when I use it on my device with 2.3.5 it is erratic. 

Any pointers to this issue would be of great help.

**Comment by JakeWharton** [comment]
This is probably because on 4.0+ the native action bar's tabs are outside of the content view (managed by the window) and on pre-4.0 they are inside the content view (managed by ActionBarSherlock).

Two things: only enable bezel swipe to open the drawer and don't slide the content, have the drawer slide in on top of it. This is the recommendations of the [design guidelines](http://developer.android.com/design/patterns/navigation-drawer.html).

**Comment by JJCodeTry** [comment]
Thanks for the reply.

Tried SlidingMenu to slide only for content and not for whole window.

setSlidingActionBarEnabled(false);

This has couple of issues :

This makes the app show a blank white page when it is loaded first. I have multiple tabs shown in action bar , so the first tab is shown as selected but the content is empty.
If I slide when say I am in tab 2 , then the back page (or behind page) content is visible but it also overlaps with what is shown currently on tab2.

This one does not look like Sherlock issue.
