### ISSUE TITLE
Wrong VersionName in AndroidManifest.xml

### ISSUE THREAD

**Issue by SimonStefan** [JakeWharton/ActionBarSherlock#987]
android:versionName in AndroidManifest is still 4.2.0 and not 4.3.1

**Comment by JakeWharton** [comment]
This is fixed on the dev branch. Also it really makes no difference since it has zero effect.

**Comment by curioustechizen** [comment]
@JakeWharton Unfortunately, it does have an effect. I spent an hour debugging an ABS issues where I wasn't seeing some errors but my teammate was. The first thing I compared was the `versionCode` and `versionName` to ensure we were using the same version of ABS.

Turns out we weren't and that was the root cause of the issue :-( . I finally figured it out from pom.xml - but that was just by chance (we aren't using Maven).
